/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Tool = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'usageCount' : IDL.Nat,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'iconUrl' : IDL.Text,
  'favoriteCount' : IDL.Nat,
});
export const ToolCategory = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const ToolPage = IDL.Record({
  'id' : IDL.Nat,
  'files' : IDL.Vec(ExternalBlob),
  'title' : IDL.Text,
  'content' : IDL.Text,
  'category' : ToolCategory,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'badges' : IDL.Vec(IDL.Text),
  'favoriteTools' : IDL.Vec(IDL.Nat),
  'memberships' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBadgeToProfile' : IDL.Func([IDL.Text], [], []),
  'addToolCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addToolPage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'findToolByName' : IDL.Func([IDL.Text], [IDL.Vec(Tool)], ['query']),
  'getAllToolCategories' : IDL.Func([], [IDL.Vec(ToolCategory)], ['query']),
  'getAllToolPages' : IDL.Func([], [IDL.Vec(ToolPage)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getToolCategory' : IDL.Func([IDL.Nat], [IDL.Opt(ToolCategory)], ['query']),
  'getToolPage' : IDL.Func([IDL.Nat], [IDL.Opt(ToolPage)], ['query']),
  'getToolPagesByCategory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ToolPage)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeTools' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveToolToFavorites' : IDL.Func([IDL.Nat], [], []),
  'trackToolUsage' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Tool = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'usageCount' : IDL.Nat,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'iconUrl' : IDL.Text,
    'favoriteCount' : IDL.Nat,
  });
  const ToolCategory = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const ToolPage = IDL.Record({
    'id' : IDL.Nat,
    'files' : IDL.Vec(ExternalBlob),
    'title' : IDL.Text,
    'content' : IDL.Text,
    'category' : ToolCategory,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'badges' : IDL.Vec(IDL.Text),
    'favoriteTools' : IDL.Vec(IDL.Nat),
    'memberships' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBadgeToProfile' : IDL.Func([IDL.Text], [], []),
    'addToolCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addToolPage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'findToolByName' : IDL.Func([IDL.Text], [IDL.Vec(Tool)], ['query']),
    'getAllToolCategories' : IDL.Func([], [IDL.Vec(ToolCategory)], ['query']),
    'getAllToolPages' : IDL.Func([], [IDL.Vec(ToolPage)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getToolCategory' : IDL.Func([IDL.Nat], [IDL.Opt(ToolCategory)], ['query']),
    'getToolPage' : IDL.Func([IDL.Nat], [IDL.Opt(ToolPage)], ['query']),
    'getToolPagesByCategory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ToolPage)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeTools' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveToolToFavorites' : IDL.Func([IDL.Nat], [], []),
    'trackToolUsage' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };