/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Tool {
  'id' : bigint,
  'name' : string,
  'usageCount' : bigint,
  'slug' : string,
  'description' : string,
  'category' : string,
  'iconUrl' : string,
  'favoriteCount' : bigint,
}
export interface ToolCategory {
  'id' : bigint,
  'name' : string,
  'description' : string,
}
export interface ToolPage {
  'id' : bigint,
  'files' : Array<ExternalBlob>,
  'title' : string,
  'content' : string,
  'category' : ToolCategory,
}
export interface UserProfile {
  'bio' : string,
  'displayName' : string,
  'badges' : Array<string>,
  'favoriteTools' : Array<bigint>,
  'memberships' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBadgeToProfile' : ActorMethod<[string], undefined>,
  'addToolCategory' : ActorMethod<[string, string], bigint>,
  'addToolPage' : ActorMethod<
    [string, string, bigint, Array<ExternalBlob>],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'findToolByName' : ActorMethod<[string], Array<Tool>>,
  'getAllToolCategories' : ActorMethod<[], Array<ToolCategory>>,
  'getAllToolPages' : ActorMethod<[], Array<ToolPage>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getToolCategory' : ActorMethod<[bigint], [] | [ToolCategory]>,
  'getToolPage' : ActorMethod<[bigint], [] | [ToolPage]>,
  'getToolPagesByCategory' : ActorMethod<[bigint], Array<ToolPage>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeTools' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveToolToFavorites' : ActorMethod<[bigint], undefined>,
  'trackToolUsage' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];